[[LLVM]]
arch = "aarch64"
git-tree-sha1 = "4f00b53245e8fcf448e4fc5a1654a8b9bfb233d2"
llvm_version = "15"
os = "macos"

    [[LLVM.download]]
    sha256 = "15d120c806c23c0ca18411ecdbb9f7157fdfafaacc8fc19f008de7f23f011b53"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.aarch64-apple-darwin-llvm_version+15.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45481e87607ca9b85a1369e626130bb644754765"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "48d89603be6f2849740cea9a6ca1e54ef0c309e6c60cec8095120487499d447b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.aarch64-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58069799cf690fd7c53449a455e16ab00af1fd7b"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "c3bbc1ffbf0f0ae88f0ff2a42ce2a0cfc47359986204c617d610ed3d13bf8cb3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.aarch64-linux-musl-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e7673979879236933b1f7a279aee7cf00312aa1"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "db21d898062ad9225d8bd4ee621db52eaede1a3c272696dd60935ad6ba1bf115"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.armv6l-linux-gnueabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "569581202d007b967dba217e929f104d6ebf94d8"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "69d2d4fdc084e81b3bb5883f27826ac6941fd7b0a3c5c273b012d4dd6050eba7"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.armv6l-linux-musleabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "918037ea406e877670ca648f5b5a2bc6505836f3"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "173d3c41463a6e677ce1ce54833ac2c6bafea306c1b054f87e9f45aa3d18a9d6"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.armv7l-linux-gnueabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c022ab8ae7337a4dd45d84680d3124dae7cf501b"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "8323eaa81d0224ec82d63a6b66859af0eb87c12825ba37f07c2cfc2e8a729c03"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.armv7l-linux-musleabihf-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01f33a58666de4bb91b43b8049e53cda47815194"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "d0cb8e0ff0fbbce2fedd74dbaf7f953394ea993527485407c7663e90dcd811ca"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.i686-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28772f6500d1062d65c9fba9a8fe91ac36eb910e"
llvm_version = "15"
os = "windows"

    [[LLVM.download]]
    sha256 = "0a80dd047104c248dc6db16819e9d937e1f2e540ce8fb2e3825e36cb052f45da"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.i686-w64-mingw32-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04d6923886098f4a379851c46672da4504a90ade"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "0e91b4aa222a9e2d8a569514afe9569a57a04f8d8812f36772926898c9a5d438"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.powerpc64le-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "9d7ce72f03ed5a95cca9077312dc36af03535de2"
llvm_version = "15"
os = "macos"

    [[LLVM.download]]
    sha256 = "96fb68e217def289b034ce5e76a03f990fb7c35c938b14a2846bba0799e2c55a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-apple-darwin-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f313af2cda54ea980a851e798138e4bb037e5f59"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "78921f8fd84683378870e30e3fb6c21f9d49a601429ef6e3c7adcba9f135105b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f313af2cda54ea980a851e798138e4bb037e5f59"
libc = "glibc"
llvm_version = "15"
os = "linux"
sanitize = "memory"

    [[LLVM.download]]
    sha256 = "78921f8fd84683378870e30e3fb6c21f9d49a601429ef6e3c7adcba9f135105b"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fcd0adf0f104fd884035594bc533c072a2ddce6"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[LLVM.download]]
    sha256 = "993ef643d8855521a55bb2afaa59dd3b0584511bf582f422b6b77b394ef7981d"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-linux-musl-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "bd4d8f5c1fed6de00efe515606a4a500534f0cf3"
llvm_version = "15"
os = "freebsd"

    [[LLVM.download]]
    sha256 = "1164f1e1d3d894d45e0fa708cf01da345df3f08205372ad11bee04fe03e10eb1"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-unknown-freebsd-llvm_version+15.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "035b75b6eaa1cc9c6a5316974caff6dcdcce5dac"
llvm_version = "15"
os = "windows"

    [[LLVM.download]]
    sha256 = "f1735fe6951a7615879c760ff0da91a3bf0a7a55457085026379e8a052d3c9a2"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-w64-mingw32-cxx11-llvm_version+15.tar.gz"
[[LLVM]]
arch = "aarch64"
git-tree-sha1 = "d3ed7795bb37d5fa025b8fc04f51fcce80a1fedb"
llvm_version = "15.asserts"
os = "macos"

    [[LLVM.download]]
    sha256 = "2dd51aad478f90f179b415a2d4378eff7dcb25bf3c826024f8da8272f4486c98"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.aarch64-apple-darwin-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ef0dcf34622f35f91374eb1bc7e0b1264d1a135"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "47168dc19e3bff2823dfc4d0010b692543cacba9a54d7af2bcbf13deba7367dd"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.aarch64-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2fb17d496fdf8e1e097df2bd7b5e5ca1d0086a4"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "f164686f8ff04504b8c1ffc8420fd3095f66f46ed57188bf114a0a795a5bc446"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.aarch64-linux-musl-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c41b9e95c6d2168173976778cfaff83db938254"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "1f2ec9c293fc97499e809b20759992988478c050850eedf498bca272cc318e84"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.armv6l-linux-gnueabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ce97945ce05fcef137b7b34ef66e5db0945c204"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "43b5569223b1a62f34b627766c63cc5010527dc13dded3e3d96c9c90a3f0a2b3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.armv6l-linux-musleabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65d770612023c51ab03b2658a5b1aec4c26996a3"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "d125908e3018eb3bc400664855e74a0cb9c1c2431eec4bc27cd3c39b5b56ffe9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.armv7l-linux-gnueabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e315a117f86abb65ffdbe1e20659e158ab2b660e"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "410f7b0e027f3fe4c1d42d7d25b3857674207fe2427f1b8495f55d543969e123"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.armv7l-linux-musleabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "048b23910711be6e82e79423949ed0454a50c6dd"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "519cc649b6438de6ef3b7e47b6bd40444f69fee725d3a753a2e3b80d8e1fdbc3"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.i686-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94702e1d41b12413889cb52a505595410ce2becb"
llvm_version = "15.asserts"
os = "windows"

    [[LLVM.download]]
    sha256 = "a927ba4e32ad8e2bafe09f8b930390deeb0e37b6a74d4b164b11c337ca72d918"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.i686-w64-mingw32-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e0afc66c3f5dc06a4e34e6b6e062101cfd13a8f"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "b9a563e95129c8b4200772e5908c83dd7515879b360e3da0cb746cf14b49119a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.powerpc64le-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "a6edad5dbfb2045327a449a9bc50009ebe4a9d38"
llvm_version = "15.asserts"
os = "macos"

    [[LLVM.download]]
    sha256 = "3fd8a3567e70517da1ce9c82fd1d32487f5183fb284345eefcfa5741fd77312a"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-apple-darwin-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d15e2bd12c25c632b6a96a9042b3603a0d3ffbac"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "e0474c6844a6bc092701455506864ade55d1ecd63be886fecd6fc52b6515df01"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d15e2bd12c25c632b6a96a9042b3603a0d3ffbac"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"
sanitize = "memory"

    [[LLVM.download]]
    sha256 = "e0474c6844a6bc092701455506864ade55d1ecd63be886fecd6fc52b6515df01"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18161134f98915921dae1134e4b7427d5597d2ef"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[LLVM.download]]
    sha256 = "7eb2bf286dc747a6d9d233ab0b1266ce56e22a8fccb70b4c45b489cb7ce13413"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-linux-musl-cxx11-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
git-tree-sha1 = "87c8692ee0807bb7f43b2cb8a10feff504826107"
llvm_version = "15.asserts"
os = "freebsd"

    [[LLVM.download]]
    sha256 = "2b64eae065ba3edf3aff3f190176e11703546c6c3d3e33fcf8cb3c2a2fe833b0"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-unknown-freebsd-llvm_version+15.asserts.tar.gz"
[[LLVM]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a952da810dbf04465b20589bd0900eac6b058e4"
llvm_version = "15.asserts"
os = "windows"

    [[LLVM.download]]
    sha256 = "5b655bc4afafc422cb3f75da291ee65108e11de2383b841daae3c310d434d6e9"
    url = "https://github.com/JuliaBinaryWrappers/LLVM_jll.jl/releases/download/LLVM-v15.0.7+11/LLVM.v15.0.7.x86_64-w64-mingw32-cxx11-llvm_version+15.asserts.tar.gz"
